/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 The sidebars can be generated from the filesystem, or explicitly defined here.
 Create as many sidebars as you want.
 */

 module.exports = {
    myAutogeneratedSidebar: [
      {
        type: 'autogenerated',
        dirName: '.', // '.' means the current docs folder
      },
      {
        type: 'link',
        label: 'SDK repo', // The link label
        href: 'https://github.com/terra-money/warp-sdk', // The external URL
      },
      {
        type: 'link',
        label: 'Contract repo', // The link label
        href: 'https://github.com/terra-money/warp-contracts', // The external URL
      },



    ],
  };